### ISSUE TITLE
Crash when connecting to a homeserver URL with a subpath

### ISSUE THREAD

**Issue by michaelnew** [vector-im/riotX-android#133]
My homeserver lives at https://mikenew.io/matrix, but Riot crashes immediately if I try to log in:
```
FATAL EXCEPTION: main
Process: im.vector.riotredesign, PID: 22058
java.lang.IllegalArgumentException: baseUrl must end in /: https://mikenew.io/matrix
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:515)
at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458)
at im.vector.matrix.android.internal.auth.DefaultAuthenticator.buildAuthAPI(DefaultAuthenticator.kt:89)
at im.vector.matrix.android.internal.auth.DefaultAuthenticator.access$buildAuthAPI(DefaultAuthenticator.kt:38)
at im.vector.matrix.android.internal.auth.DefaultAuthenticator$authenticate$2.invokeSuspend(DefaultAuthenticator.kt:70)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by bmarty** [comment]
Thanks for reporting. It should work now

**Comment by michaelnew** [comment]
Just tested it and it works great. Thanks 👍
