### ISSUE TITLE
Crash after setting up cross-signing

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#1352]
I logged into a test account, finished the cross-signing setup (enter recovery passphrase, repeat it, enter account password) then riotX crashed.

Version is 0.19.0 from F-Droid, crash from adb here. I don't know how to trigger a rageshake from an android emulator.

```
05-10 15:25:57.461  7462  7489 E REALM_JNI: jni: ThrowingException 2, Out of range  in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsList.cpp line 135(requested: 2 valid: 1), .
05-10 15:25:57.463  7462  7489 E REALM_JNI: Exception has been thrown: Out of range  in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsList.cpp line 135(requested: 2 valid: 1)
--------- beginning of crash
05-10 15:25:57.499  7462  7489 E AndroidRuntime: FATAL EXCEPTION: Crypto_Thread
05-10 15:25:57.499  7462  7489 E AndroidRuntime: Process: im.vector.riotx, PID: 7462
05-10 15:25:57.499  7462  7489 E AndroidRuntime: java.util.NoSuchElementException: Cannot access index 2 when size is 1. Remember to check hasNext() before using next().
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at io.realm.RealmList$RealmItr.next(RealmList.java:1110)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.addOrUpdateCrossSigningInfo(RealmCryptoStore.kt:1509)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.access$addOrUpdateCrossSigningInfo(RealmCryptoStore.kt:92)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore$setMyCrossSigningInfo$1.invoke(RealmCryptoStore.kt:1254)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore$setMyCrossSigningInfo$1.invoke(RealmCryptoStore.kt:92)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.HelperKt$doRealmTransaction$$inlined$use$lambda$1.execute(Helper.kt:62)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at io.realm.Realm.executeTransaction(Realm.java:1493)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmTransaction(Helper.kt:62)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.setMyCrossSigningInfo(RealmCryptoStore.kt:1252)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.crosssigning.DefaultCrossSigningService$initializeCrossSigning$1$1.onSuccess(DefaultCrossSigningService.kt:158)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.crypto.crosssigning.DefaultCrossSigningService$initializeCrossSigning$1$1.onSuccess(DefaultCrossSigningService.kt:151)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.extensions.ResultKt.foldToCallback(Result.kt:23)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at im.vector.matrix.android.internal.task.TaskExecutor$execute$1.invokeSuspend(TaskExecutor.kt:52)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-10 15:25:57.499  7462  7489 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
05-10 15:25:57.508  1947  7664 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-10 15:25:57.516  1947  4013 W ActivityTaskManager:   Force finishing activity im.vector.riotx/.features.home.HomeActivity
05-10 15:25:57.537  7462  7489 I Process : Sending signal. PID: 7462 SIG: 9
```

**Comment by Bubu** [comment]
I did manage to send a rageshake, refenreced this issue there.

**Comment by BillCarsonFr** [comment]
fixed by https://github.com/vector-im/riotX-android/pull/1365
