### ISSUE TITLE
RiotX crash in latest version when clicking "Encryption upgrade available"

### ISSUE THREAD

**Issue by Porkepix** [vector-im/riotX-android#1360]
Since latest release, RiotX present an "Encryption upgrade available banner". I tried to click it to see what did it want to do or present, and it resulted to a spinner that ended, after a couple of tens of seconds in a crash of the application. Here's the `adb logcat -v threadtime`:

```
05-12 17:34:44.219  8148  9599 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-5
05-12 17:34:44.219  8148  9599 E AndroidRuntime: Process: im.vector.riotx, PID: 8148
05-12 17:34:44.219  8148  9599 E AndroidRuntime: NetworkConnection(ioException=java.net.SocketTimeoutException: timeout)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at im.vector.matrix.android.internal.network.Request.execute(Request.kt:56)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at im.vector.matrix.android.internal.network.Request$execute$1.invokeSuspend(Request.kt)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:334)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: Caused by: java.net.SocketTimeoutException: timeout
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:666)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:675)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:142)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:99)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:56)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at im.vector.matrix.android.internal.network.AccessTokenInterceptor.intercept(AccessTokenInterceptor.kt:39)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okreplay.OkReplayInterceptor.intercept(OkReplayInterceptor.java:10)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:150)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at im.vector.matrix.android.internal.network.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:35)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at im.vector.matrix.android.internal.network.TimeOutInterceptor.intercept(TimeOutInterceptor.kt:47)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
05-12 17:34:44.219  8148  9599 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runW
```

Environment is Android Marshmallow (6.0.1) on a Sony Z3 Compact with stock rom.

**Comment by ManDay** [comment]
In my experience (Android 9, Kernel 4.9.117+, RiotX 0.19.0), after the initial installation and login I was presented with the banner and clicking on it went all right up to the point where I RiotX was trying to publish the keys, which eventually aborted with a Java exeception "timeout". In a later attempt, I had the same crash described above. An even later attempt today fully went through with the progress with no error.
