### ISSUE TITLE
sometimes it chashes

### ISSUE THREAD

**Issue by 532910** [vector-im/riotX-android#1609]
```
 629   629 D AndroidRuntime: Shutting down VM
 629   629 E AndroidRuntime: FATAL EXCEPTION: main
 629   629 E AndroidRuntime: Process: im.vector.app, PID: 629
 629   629 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{im.vector.app/im.vector.riotx.features.home.HomeActivity}: java.lang.IllegalArgumentException: HomeActivityViewModel takes dependencies other than initialState. It must have companion object implementing MvRxViewModelFactory with a create method returning a non-null ViewModel.
 629   629 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
 629   629 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
 629   629 E AndroidRuntime:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 629   629 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 629   629 E AndroidRuntime:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 629   629 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
 629   629 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
 629   629 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:193)
 629   629 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6718)
 629   629 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
 629   629 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 629   629 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 629   629 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: HomeActivityViewModel takes dependencies other than initialState. It must have companion object implementing MvRxViewModelFactory with a create method returning a non-null ViewModel.
 629   629 E AndroidRuntime:    at com.airbnb.mvrx.MvRxFactory.create(MvRxFactory.kt:23)
 629   629 E AndroidRuntime:    at com.airbnb.mvrx.MvRxViewModelProvider.get(MvRxViewModelProvider.kt:27)
 629   629 E AndroidRuntime:    at com.airbnb.mvrx.MvRxViewModelProvider.get$default(MvRxViewModelProvider.kt:2)
 629   629 E AndroidRuntime:    at im.vector.riotx.features.home.HomeActivity$$special$$inlined$viewModel$1.invoke(MvRxExtensions.kt:6)
 629   629 E AndroidRuntime:    at im.vector.riotx.features.home.HomeActivity$$special$$inlined$viewModel$1.invoke(Unknown Source:0)
 629   629 E AndroidRuntime:    at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:6)
 629   629 E AndroidRuntime:    at im.vector.riotx.features.home.HomeActivity.getHomeActivityViewModel(Unknown Source:7)
 629   629 E AndroidRuntime:    at im.vector.riotx.features.home.HomeActivity.onCreate(HomeActivity.kt:27)
 629   629 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:7144)
 629   629 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:7135)
 629   629 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
 629   629 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
 629   629 E AndroidRuntime:    ... 11 more
2405 20846 W ActivityManager:   Force finishing activity im.vector.app/im.vector.riotx.features.home.HomeActivity
```

**Comment by bmarty** [comment]
Already fixed in beta-4, which is not release yet

**Comment by bmarty** [comment]
Released

**Comment by 532910** [comment]
i confirm this is fixed
