### ISSUE TITLE
Crash from Rageshake

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#339]
https://github.com/matrix-org/riot-android-rageshakes/issues/6012

```
Thread: Crypto_Thread, Exception: kotlin.KotlinNullPointerException
at im.vector.matrix.android.internal.crypto.algorithms.megolm.MXMegolmDecryption.onRoomKeyEvent(MXMegolmDecryption.kt:212)
at im.vector.matrix.android.internal.crypto.CryptoManager.onRoomKeyEvent(CryptoManager.kt:681)
at im.vector.matrix.android.internal.crypto.CryptoManager.access$onRoomKeyEvent(CryptoManager.kt:96)
at im.vector.matrix.android.internal.crypto.CryptoManager$onToDeviceEvent$1.invokeSuspend(CryptoManager.kt:653)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by bmarty** [comment]
crash on `forwardingCurve25519KeyChain.add(senderKey!!)`, already fixed here: 466a39d239d7a28ce8f3a3c2b95de2e89e0a9260
