### ISSUE TITLE
Crash when sharing image from e2e room

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#628]
In e2e room try to share on image form the timeline -> crash

```
Thread: main, Exception: java.lang.NullPointerException: uriString
at android.net.Uri$StringUri.(Uri.java:490)
at android.net.Uri$StringUri.(Uri.java:480)
at android.net.Uri.parse(Uri.java:452)
at im.vector.riotx.features.home.room.detail.RoomDetailFragment.handleActions(RoomDetailFragment.kt:882)
at im.vector.riotx.features.home.room.detail.RoomDetailFragment.access$handleActions(RoomDetailFragment.kt:131)
```
https://github.com/matrix-org/riot-android-rageshakes/issues/7511

**Comment by bmarty** [comment]
The crash has been fixed by removing the share action on image in e2e room.
This issue is replaced by #677
