### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by fynngodau** [vector-im/riotX-android#804]
RiotX crashes upon launch since a few days. Here's the relevant exception:

```
01-04 10:24:02.932 13487 13487 E AndroidRuntime: FATAL EXCEPTION: main
01-04 10:24:02.932 13487 13487 E AndroidRuntime: Process: im.vector.riotx.debug, PID: 13487
01-04 10:24:02.932 13487 13487 E AndroidRuntime: java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/im.vector.riotx.debug/files/matrix-sdk-auth.realm': Realm file decryption failed Path:. (Realm file decryption failed Path: /data/data/im.vector.riotx.debug/files/matrix-sdk-auth.realm) (/data/data/im.vector.riotx.debug/files/matrix-sdk-auth.realm) in /Users/Nabil/Dev/realm/master2/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/im.vector.riotx.debug/files/matrix-sdk-auth.realm': Realm file decryption failed Path:. (Realm file decryption failed Path: /data/data/im.vector.riotx.debug/files/matrix-sdk-auth.realm) (/data/data/im.vector.riotx.debug/files/matrix-sdk-auth.realm) in /Users/Nabil/Dev/realm/master2/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:428)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.internal.auth.db.RealmPendingSessionStore.getPendingSessionData(RealmPendingSessionStore.kt:45)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.internal.auth.DefaultAuthenticationService.<init>(DefaultAuthenticationService.kt:58)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.internal.di.DaggerMatrixComponent.getDefaultAuthenticationService(DaggerMatrixComponent.java:123)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.internal.di.DaggerMatrixComponent.injectMatrix(DaggerMatrixComponent.java:198)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.internal.di.DaggerMatrixComponent.inject(DaggerMatrixComponent.java:195)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.api.Matrix.<init>(Matrix.kt:57)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.api.Matrix.<init>(Matrix.kt:47)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.matrix.android.api.Matrix$Companion.getInstance(Matrix.kt:87)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.core.di.VectorModule$Companion.providesMatrix(VectorModule.kt:57)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.core.di.VectorModule.providesMatrix(Unknown Source:2)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.core.di.VectorModule_ProvidesMatrixFactory.providesMatrix(VectorModule_ProvidesMatrixFactory.java:31)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.core.di.DaggerVectorComponent.matrix(DaggerVectorComponent.java:258)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.core.di.DaggerVectorComponent.authenticationService(DaggerVectorComponent.java:354)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.core.di.DaggerVectorComponent.injectVectorApplication(DaggerVectorComponent.java:396)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.core.di.DaggerVectorComponent.inject(DaggerVectorComponent.java:254)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at im.vector.riotx.VectorApplication.onCreate(VectorApplication.kt:85)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
01-04 10:24:02.932 13487 13487 E AndroidRuntime: 	... 8 more
01-04 10:24:02.946   838   855 W ActivityManager:   Force finishing activity im.vector.riotx.debug/im.vector.riotx.features.Alias
01-04 10:24:02.956 13487 13487 I Process : Sending signal. PID: 13487 SIG: 9
01-04 10:24:03.003   838  1354 I ActivityManager: Process im.vector.riotx.debug (pid 13487) has died: fore TOP 
```

**Comment by MegaArthur** [comment]
Sounds like wiping app data could help (remember about the decryption keys)

**Comment by fynngodau** [comment]
Yes, I too believe that would workaround this issue, but it's not really a fix.

**Comment by MegaArthur** [comment]
It could be caused by data corruption, the only fix Riot could implement is a prompt saying "it's fucked, wipe data"

I am not sure, though

**Comment by leo-lb** [comment]
It happened to me several times in several months, I had to clear data to get going again. It's pretty annoying because it means you lose your E2EE key, even if, with cross signing, it's not so much of a big deal anymore. I'm not sure I'm affected by this exact bug because I cannot access any kind of logs (my device is not rooted either and the app doesnt open), but the symptions match.
