### ISSUE TITLE
crash upon login on android 5.1.1

### ISSUE THREAD

**Issue by foresto** [vector-im/riotX-android#896]
Using RiotX 0.13.0-dev from f-droid, on an android 5.1.1 (LineageOS 12.1) device:

Launching RiotX for the first time, I am able to progress through the first few screens, including "Connect to matrix.org". As soon as I enter my username and password and tap the Sign In button, a "Welcome to the beta" screen appears for a fraction of a second, and then the app crashes.

Attempts to restart the app yield a crash report dialog, followed by a blank white screen that does nothing. When I exit to the android home screen, I find another "application has stopped" (crash) message waiting for me.

logcat output from the first crash:

    V/WindowManager( 2322): rotationForOrientationLw(orient=-1, last=0); user=0 
    D/ConnectivityService( 2322): updateNetworkScore for NetworkAgentInfo [WIFI () - 103] to 60
    D/ConnectivityService( 2322): rematching NetworkAgentInfo [WIFI () - 103]
    D/ConnectivityService( 2322): Network NetworkAgentInfo [WIFI () - 103] was already satisfying request 1. No change.
    D/ConnectivityService( 2322): notifyType AVAILABLE for NetworkAgentInfo [WIFI () - 103]
    D/ConnectivityManager.CallbackHandler( 4507): CM callback handler got msg 524290
    W/keystore( 1763): Could not read CACERT_session_db_2a8329155df60af39b9c3a37296aeaf8
    W/keystore( 1763): Could not read CACERT_crypto_module_2a8329155df60af39b9c3a37296aeaf8
    W/keystore( 1763): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1763): ION allocation  failed
    W/keystore( 1763): device couldn't sign data
    W/OpenSSL-keystore-rsa(12157): No valid signature returned
    W/keystore( 1763): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1763): ION allocation  failed
    W/keystore( 1763): device couldn't sign data
    W/OpenSSL-keystore-rsa(12157): No valid signature returned
    W/keystore( 1763): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1763): ION allocation  failed
    W/keystore( 1763): device couldn't sign data
    W/OpenSSL-keystore-rsa(12157): No valid signature returned
    W/keystore( 1763): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1763): ION allocation  failed
    W/keystore( 1763): device couldn't sign data
    W/OpenSSL-keystore-rsa(12157): No valid signature returned
    W/keystore( 1763): Could not read CACERT_matrix-sdk-auth
    W/ResourceType( 4507): For resource 0x01030224, entry index(548) is beyond type entryCount(41)
    W/ResourceType( 4507): For resource 0x01030224, entry index(548) is beyond type entryCount(41)
    W/ResourceType( 4507): For resource 0x01030203, entry index(515) is beyond type entryCount(41)
    W/ResourceType( 4507): For resource 0x010301fe, entry index(510) is beyond type entryCount(41)
    W/ResourceType( 4507): For resource 0x01030201, entry index(513) is beyond type entryCount(41)
    W/ResourceType( 4507): For resource 0x01030200, entry index(512) is beyond type entryCount(41)
    W/ResourceType( 4507): For resource 0x01030202, entry index(514) is beyond type entryCount(41)
    I/Timeline(12157): Timeline: Activity_launch_request id:im.vector.riotx time:3148695
    I/ActivityManager( 2322): START u0 {cmp=im.vector.riotx/.features.home.HomeActivity (has extras)} from uid 10065 on display 0
    V/WindowManager( 2322): addAppToken: AppWindowToken{343d6cb3 token=Token{32d6da22 ActivityRecord{40aebed u0 im.vector.riotx/.features.home.HomeActivity t9488}}} to stack=1 task=9488 at 1
    E/QCOMKeyMaster( 1763): ION allocation  failed
    W/keystore( 1763): device couldn't sign data
    W/OpenSSL-keystore-rsa(12157): No valid signature returned
    W/art     (12157): Long monitor contention event with owner method=int com.android.org.conscrypt.NativeCrypto.RSA_private_decrypt(int, byte[], byte[], long, int) from NativeCrypto.java:4294967294 waiters=0 for 102ms
    W/ResourceType(12157): For resource 0x01030224, entry index(548) is beyond type entryCount(41)
    W/ResourceType(12157): For resource 0x01030224, entry index(548) is beyond type entryCount(41)
    V/WindowManager( 2322): Adding window Window{23b759e9 u0 im.vector.riotx/im.vector.riotx.features.home.HomeActivity} at 10 of 15 (after Window{bdfccc3 u0 im.vector.riotx/im.vector.riotx.features.login.LoginActivity})
    V/WindowManager( 2322): Adding window Window{3d98210f u0 im.vector.riotx/im.vector.riotx.features.home.HomeActivity} at 10 of 16 (before Window{23b759e9 u0 im.vector.riotx/im.vector.riotx.features.home.HomeActivity})
    I/ActivityManager( 2322): Displayed im.vector.riotx/.features.home.HomeActivity: +338ms
    W/ResourceType(12157): No package identifier when getting value for resource number 0x00000000
    W/ResourceType(12157): No package identifier when getting value for resource number 0x00000000
    D/AndroidRuntime(12157): Shutting down VM
    E/AndroidRuntime(12157): FATAL EXCEPTION: main
    E/AndroidRuntime(12157): Process: im.vector.riotx, PID: 12157
    E/AndroidRuntime(12157): android.view.InflateException: Binary XML file line #74: Error inflating class <unknown>
    E/AndroidRuntime(12157): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
    E/AndroidRuntime(12157): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
    E/AndroidRuntime(12157): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    E/AndroidRuntime(12157): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    E/AndroidRuntime(12157): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    E/AndroidRuntime(12157): 	at im.vector.riotx.core.platform.VectorBaseFragment.onCreateView(VectorBaseFragment.kt:105)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:292)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1227)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1396)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1474)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1539)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2330)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2117)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2072)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1974)
    E/AndroidRuntime(12157): 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:418)
    E/AndroidRuntime(12157): 	at android.os.Handler.handleCallback(Handler.java:739)
    E/AndroidRuntime(12157): 	at android.os.Handler.dispatchMessage(Handler.java:95)
    E/AndroidRuntime(12157): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime(12157): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
    E/AndroidRuntime(12157): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime(12157): 	at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime(12157): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    E/AndroidRuntime(12157): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    E/AndroidRuntime(12157): Caused by: java.lang.reflect.InvocationTargetException
    E/AndroidRuntime(12157): 	at java.lang.reflect.Constructor.newInstance(Native Method)
    E/AndroidRuntime(12157): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
    E/AndroidRuntime(12157): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
    E/AndroidRuntime(12157): 	... 25 more
    E/AndroidRuntime(12157): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
    E/AndroidRuntime(12157): 	at android.content.res.Resources.getValue(Resources.java:1343)
    E/AndroidRuntime(12157): 	at android.content.res.Resources.getValue(Resources.java:1323)
    E/AndroidRuntime(12157): 	at androidx.appcompat.content.res.AppCompatResources.isColorInt(AppCompatResources.java:165)
    E/AndroidRuntime(12157): 	at androidx.appcompat.content.res.AppCompatResources.inflateColorStateList(AppCompatResources.java:112)
    E/AndroidRuntime(12157): 	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:78)
    E/AndroidRuntime(12157): 	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.createDefaultColorStateList(BottomNavigationMenuView.java:498)
    E/AndroidRuntime(12157): 	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.<init>(BottomNavigationMenuView.java:113)
    E/AndroidRuntime(12157): 	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.<init>(BottomNavigationMenuView.java:98)
    E/AndroidRuntime(12157): 	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:145)
    E/AndroidRuntime(12157): 	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:133)
    E/AndroidRuntime(12157): 	... 28 more
    W/ActivityManager( 2322):   Force finishing activity 1 im.vector.riotx/.features.home.HomeActivity
    I/OpenGLRenderer( 2322): Initialized EGL, version 1.4
    W/ActivityManager( 2322): Activity pause timeout for ActivityRecord{40aebed u0 im.vector.riotx/.features.home.HomeActivity t9488 f}
    V/WindowManager( 2322): rotationForOrientationLw(orient=5, last=0); user=0 
    W/ResourceType( 4507): No package identifier when getting value for resource number 0x00000000
    W/PackageManager( 4507): Failure retrieving resources for im.vector.riotx: Resource ID #0x0
    I/Timeline( 4940): Timeline: Activity_idle id: android.os.BinderProxy@138d037a time:3149851
    I/Timeline( 2322): Timeline: Activity_windows_visible id: ActivityRecord{3d9180e8 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t9473} time:3150105
    I/Timeline( 2322): Timeline: Activity_windows_visible id: ActivityRecord{40aebed u0 im.vector.riotx/.features.home.HomeActivity t9488 f} time:3150305
    W/OpenGLRenderer( 4940): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
    W/OpenGLRenderer( 4940): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

**Comment by foresto** [comment]
I got around the crash by reverting to the LineageOS default themes. (I had non-default themes for the style, status bar, navigation bar, and wallpapers. One of those must have been causing trouble.) RiotX then started and logged in normally. After that, I went back to my custom themes and RiotX continues to work, so I guess the crash only occurs during first-time login/setup.
